// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data.Migrations;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260605173353_DataSeededDepartamentos")]
    partial class DataSeededDepartamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Titulo = "Departamento de Sistemas y Computación"
                        },
                        new
                        {
                            Id = 2,
                            Titulo = "Departamento de Ingeniería Industrial"
                        },
                        new
                        {
                            Id = 3,
                            Titulo = "Departamento de Ingeniería Civil"
                        },
                        new
                        {
                            Id = 4,
                            Titulo = "Departamento de Ciencias de la Tierra"
                        },
                        new
                        {
                            Id = 5,
                            Titulo = "Departamento de Ciencias Economico-Administrativas"
                        },
                        new
                        {
                            Id = 6,
                            Titulo = "Departamento de Ingeniería Mecánica"
                        },
                        new
                        {
                            Id = 7,
                            Titulo = "Departamento de Ingeniería Química"
                        },
                        new
                        {
                            Id = 8,
                            Titulo = "Departamento de Ciencias Basicas"
                        });
                });

            modelBuilder.Entity("WebApp.Models.Proyector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaDeAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDeBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDeSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Situacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Proyectores", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
